# Generated by Django 4.1.5 on 2023-01-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_useractivities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserActivities',
            new_name='UserActivity',
        ),
    ]
