version: "3"
services:
  inventory_app:
    container_name: "inventory_app"
    image: postgres
    environment:
      POSTGRES_USER: "inventory_user"
      POSTGRESS_PASSWORD: "password"
      PGDATA: "/data/inventory_app"
    volumes:
      - inventory_app:/data/inventory_app
    ports:
      - "5434:5434"
    networks:
      - "inventory_app_net"
    restart: unless-stopped
networks:
  inventory_app_net:
    driver: bridge
volumes:
  inventory_app:
